DjangoWebSocket/myDjango/myDjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('songs/',include('songs.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DjangoWebSocket/myDjango/songs/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from . import testws
from django.conf import settings
from django.conf.urls.static import static

#네임스페이스로 name을 구별하는데 사용한다. songs:detail
app_name = 'songs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('admin/', admin.site.urls)
]

DjangoWebSocket/myDjango/songs/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    #Question.objects.all() 의 결과가 <QuerySet [<Question: Question object (1)>]> 나온다. 이것을
    #텍스트로 나오게 하려면 __str__을 확장해준다.
    def __str__(self): #
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

DjangoWebSocket/myDjango/songs/views.py
from django.shortcuts import render,get_object_or_404
from django.template.context_processors import request
from django.template import loader
from django.http.response import HttpResponse
from django.http import Http404,HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question,Choice


def index(request):
    #질문 객체의 pub_date로 정렬 한 후 리스트 0~5까지만 보여준다.
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    template = loader.get_template('index.html')
    context = {'latest_question_list': latest_question_list}
    return HttpResponse(template.render(context, request))

    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)



def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("질문 페이지가 존재 하지 않습니다.")
#     return render(request, 'detail.html', {'question': question})
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 다시 질분을 디스플레이 해준다.
        return render(request, 'songs/detail.html', {
            'question': question,
            'error_message': "선택을 해주세요.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        #일반적인 서버사이드 리다이렉션방식이다.
        #reverse -> 'results/3'을 리버스해주어서 '3/results' = 'songs/3/results'가된다.
        return HttpResponseRedirect(reverse('songs:results', args=(question.id,)))
    
 
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'results.html'
       
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'results.html', {'question': question})

DjangoWebSocket/myDjango/songs/templates/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>상세</title>
</head>

<body>
	<h1>{{ question.question_text }}</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action="{% url 'songs:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
	    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
	{% endfor %}
	<input type="submit" value="Vote">
	</form>
</body>
</html>

DjangoWebSocket/myDjango/songs/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>설문조사</title>
</head>

<body>
	{% if latest_question_list %}
	    <ul>
	    {% for question in latest_question_list %}
	        <li><a href="{% url 'songs:detail' question.id %}">{{ question.question_text }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
</body>
</html>

DjangoWebSocket/myDjango/songs/templates/results.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>결과</title>
</head>

<body>
	<h1>{{ question.question_text }}</h1>
	<ul>
	{% for choice in question.choice_set.all %}
	    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
	</ul>
	<a href="{% url 'songs:detail' question.id %}">Vote again?</a>
</body>
</html>